### ISSUE TITLE
请问可以附上您的static文件夹吗，js文件和popper文件有些很难找得到！

### ISSUE THREAD

**Issue by unclesix06** [stacklens/django_blog_tutorial#1]

**Comment by stacklens** [comment]
static里都是三方库，所以没有提供。也是为了让读者自己动手尝试下载及使用第三方库。
另外教程里更新了popper的下载地址：[popper](https://unpkg.com/popper.js@1.14.4/dist/umd/popper.js)

**Comment by stacklens** [comment]
考虑了一下，还是把static文件夹上传了，大家根据需要使用吧~
