### ISSUE TITLE
ckeditor static file missing

### ISSUE THREAD

**Issue by ahaliu1** [stacklens/django_blog_tutorial#2]
It seems that comment part is unavailable now. Missing file "ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js'"
![image](https://user-images.githubusercontent.com/30023830/57205023-1bc05580-6fee-11e9-9161-ba5714f293c6.png)

**Comment by stacklens** [comment]
@ahaliu1 
This file is a plugin in the django-ckeditor module. It is not in the static folder. 
Instead, you need to go to the prism website to download and install it in the right place. 
There are explanations in my tutorial, [see here for details](https://www.dusaiphoto.com/article/detail/60/).
