### ISSUE TITLE
header.html登录里的注册报错

### ISSUE THREAD

**Issue by XueKX** [stacklens/django_blog_tutorial#3]
![image](https://user-images.githubusercontent.com/25972966/65853219-548d0c80-e38b-11e9-8153-653b03cb4f97.png)
Q2：请问为什么有两种登录界面  （从首页中和文章中）

**Comment by stacklens** [comment]
教程中做过两个登录系统。一个原生的，一个基于 django-allauth 的。
所以具体情况请以教程为准。
